# Домашнее задание 5

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 10)
reversed_arr = arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
a = np.diag(np.arange(10), k=0)
b = a[::-1]

total_sum = 0
for row in range(len(b)):
    n=row
    f=9
    total_sum +=b[row][f-n]
print(total_sum)

[[0 0 0 0 0 0 0 0 0 9]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


### Задание 3
Решите систему уравнений:\
4x + 2y + z = 4 \
x + 3y = 12\
5y + 4z = -3

In [3]:
from numpy import linalg

In [6]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 4, 0] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([-5.18181818,  5.72727273, 13.27272727])